[build]
  command = "echo 'No build command required'"
  publish = "public"

[[redirects]]
  from = "/templates/*"
  to = "/../templates/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
